Update README.md and renamed veriables to match others better
jmassardo/issues-to-totango pull request #40
Opened 2023-01-11 17:32 UTC by cheeragpatel

Signed-off-by: Cheerag Patel <cheeragpatel@github.com>

2023-01-11 18:19 UTC, sam1el approved these changes
looks good

2023-01-11 21:57 UTC, rockin-robinson requested changes

2023-01-11 21:57 UTC, rockin-robinson commented on README.md
>    TOTANGO_USER_NAME: "totango_user_email@email.com"
Do you mind changing this one to TASK_ASSIGNEE while we're here? I think I might have put this on the wrong line :D It's supposed to be on 64

2023-01-12 22:30 UTC, rockin-robinson approved these changes

2023-01-12 22:32 UTC, merged